services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.29.0
    container_name: audiobookshelf
#    ports:
#      - 13378:80
    volumes:
      - $DOCKER_VOLUME_PATH/audiobookshelf_audiobooks:/audiobooks
      #      - </path/to/podcasts>:/podcasts
      - hzsb-malphite:/data/storagebox
      - $DOCKER_VOLUME_PATH/audiobookshelf_config:/config
      - $DOCKER_VOLUME_PATH/audiobookshelf_metadata:/metadata
    environment:
      - TZ=Asia/Kolkata
    networks:
      - internal-net
    restart: always
volumes:
  hzsb-malphite:
    external: true
networks:
  internal-net:
    external: true
