services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.29.0
    ports:
      - 13378:80
    volumes:
      - /data/docker_volumes/audiobookshelf_audiobooks:/audiobooks
#      - </path/to/podcasts>:/podcasts
      - /data/docker_volumes/audiobookshelf_config:/config
      - /data/docker_volumes/audiobookshelf_metadata:/metadata
    environment:
      - TZ=Asia/Kolkata
    networks:
      - internal-net
    restart: always
networks:
  internal-net:
    external: true
